export const candidatos = [
    {
      id: '1',
      nombre: 'Yonhy Lescano Ancieta',
      partido: 'Acción Popular',
      foto: require('@/assets/images/perfil.png'),
      edad: 65,
      profesion: 'Abogado',
      trayectoria: 'Excongresista, ha participado activamente en la política peruana durante décadas.',
      ideologia: 'Centro',
    },
    {
      id: '2',
      nombre: 'César Acuña Peralta',
      partido: 'Alianza para el Progreso',
      foto: require('@/assets/images/perfil.png'),
      edad: 71,
      profesion: 'Empresario y político',
      trayectoria: 'Fundador de la Universidad César Vallejo, exgobernador regional de La Libertad.',
      ideologia: 'Centro derecha',
    },
    {
      id: '3',
      nombre: 'Hernando de Soto Polar',
      partido: 'Avanza País',
      foto: require('@/assets/images/perfil.png'),
      edad: 82,
      profesion: 'Economista',
      trayectoria: 'Reconocido economista con amplia experiencia internacional.',
      ideologia: 'Derecha',
    },
    {
      id: '4',
      nombre: 'Keiko Fujimori Higuchi',
      partido: 'Fuerza Popular',
      foto: require('@/assets/images/perfil.png'),
      edad: 48,
      profesion: 'Administradora de empresas',
      trayectoria: 'Excongresista, ha sido candidata presidencial en varias ocasiones.',
      ideologia: 'Derecha',
    },
    {
      id: '5',
      nombre: 'Verónika Mendoza Frisch',
      partido: 'Juntos por el Perú',
      foto: require('@/assets/images/perfil.png'),
      edad: 43,
      profesion: 'Psicóloga y política',
      trayectoria: 'Excongresista, líder de izquierda en el Perú.',
      ideologia: 'Izquierda',
    },
    {
      id: '6',
      nombre: 'Daniel Urresti Elera',
      partido: 'Podemos Perú',
      foto: require('@/assets/images/perfil.png'),
      edad: 64,
      profesion: 'Militar y político',
      trayectoria: 'Exministro del Interior, con una carrera política controvertida.',
      ideologia: 'Centro',
    },
    {
      id: '7',
      nombre: 'Pedro Castillo Terrones',
      partido: 'Perú Libre',
      foto: require('@/assets/images/perfil.png'),
      edad: 54,
      profesion: 'Profesor y sindicalista',
      trayectoria: 'Líder sindical y político de izquierda.',
      ideologia: 'Izquierda',
    },
    {
      id: '8',
      nombre: 'Rafael López Aliaga Cazorla',
      partido: 'Renovación Popular',
      foto: require('../assets/images/perfil.png'),
      edad: 61,
      profesion: 'Empresario',
      trayectoria: 'Empresario con posturas conservadoras.',
      ideologia: 'Derecha',
    },
  ];