export const candidatos = [
  {
    id: '1',
    nombre: 'Yonhy Lescano Ancieta',
    partido: 'Acción Popular',
    foto: require('@/assets/images/perfil.png'),
    edad: 65,
    profesion: 'Abogado',
    trayectoria: 'Excongresista, ha participado activamente en la política peruana durante décadas.',
    ideologia: 'Centro',
  },
  {
    id: '2',
    nombre: 'César Acuña Peralta',
    partido: 'Alianza para el Progreso',
    foto: require('@/assets/images/perfil.png'),
    edad: 71,
    profesion: 'Empresario y político',
    trayectoria: 'Fundador de la Universidad César Vallejo, exgobernador regional de La Libertad.',
    ideologia: 'Centro derecha',
  },
  {
    id: '3',
    nombre: 'Hernando de Soto Polar',
    partido: 'Avanza País',
    foto: require('@/assets/images/perfil.png'),
    edad: 82,
    profesion: 'Economista',
    trayectoria: 'Reconocido economista con amplia experiencia internacional.',
    ideologia: 'Derecha',
  },
  {
    id: '4',
    nombre: 'Keiko Fujimori Higuchi',
    partido: 'Fuerza Popular',
    foto: require('@/assets/images/perfil.png'),
    edad: 48,
    profesion: 'Administradora de empresas',
    trayectoria: 'Excongresista, ha sido candidata presidencial en varias ocasiones.',
    ideologia: 'Derecha',
  },
  {
    id: '5',
    nombre: 'Verónika Mendoza Frisch',
    partido: 'Juntos por el Perú',
    foto: require('@/assets/images/perfil.png'),
    edad: 43,
    profesion: 'Psicóloga y política',
    trayectoria: 'Excongresista, líder de izquierda en el Perú.',
    ideologia: 'Izquierda',
  },
  {
    id: '6',
    nombre: 'Daniel Urresti Elera',
    partido: 'Podemos Perú',
    foto: require('@/assets/images/perfil.png'),
    edad: 64,
    profesion: 'Militar y político',
    trayectoria: 'Exministro del Interior, con una carrera política controvertida.',
    ideologia: 'Centro',
  },
  {
    id: '7',
    nombre: 'Pedro Castillo Terrones',
    partido: 'Perú Libre',
    foto: require('@/assets/images/perfil.png'),
    edad: 54,
    profesion: 'Profesor y sindicalista',
    trayectoria: 'Líder sindical y político de izquierda.',
    ideologia: 'Izquierda',
  },
  {
    id: '8',
    nombre: 'Rafael López Aliaga Cazorla',
    partido: 'Renovación Popular',
    foto: require('../assets/images/perfil.png'),
    edad: 61,
    profesion: 'Empresario',
    trayectoria: 'Empresario con posturas conservadoras.',
    ideologia: 'Derecha',
  },
];

export const PerfilCandidato = {
  "nombre": "Julio César Espinoza",
  "edad": 60,
  "profesion": "Ingeniero Civil",
  "nacionalidad": "Peruana",
  "lugar_de_nacimiento": "Arequipa, Perú",
  "estado_civil": "Casado",
  "familia": "Tiene 3 hijos",
  "experiencia_profesional": [
    "Gerente General de la constructora \"Espinoza & Hijos\" (1995-presente)",
    "Supervisor de obras públicas en el Ministerio de Transportes y Comunicaciones (1990-1995)",
    "Ingeniero residente en la construcción del puente \"Unión\" (1988-1990)"
  ],
  "experiencia_politica": [
    "Alcalde del distrito de Miraflores (2010-2014)",
    "Regidor del distrito de Miraflores (2006-2010)"
  ],
  "participacion_organizaciones": [
    "Miembro del Colegio de Ingenieros del Perú",
    "Fundador de la ONG \"Construyendo un Futuro Mejor\""
  ],
  "ideologia": "Centro",
  "educacion": [
    "Maestría en Ingeniería Estructural, Universidad Nacional de Ingeniería",
    "Licenciatura en Ingeniería Civil, Universidad Nacional de Ingeniería"
  ],
  "redes_sociales": {
    "twitter": "https://twitter.com/JulioEspinoza",
    "facebook": "https://www.facebook.com/JulioEspinozaPeru"
  },
  "intereses": [
    "Desarrollo de infraestructura",
    "Mejora del transporte público",
    "Ordenamiento territorial",
    "Gestión de riesgos de desastres"
  ],
  "hobbies": ["Senderismo", "Lectura", "Música clásica"],
  "motivaciones": "Desea mejorar la infraestructura del país y la calidad de vida de los ciudadanos",
  "valores": ["Honestidad", "Responsabilidad", "Compromiso", "Solidaridad"],
  "vision_de_futuro": "Un Perú con una infraestructura moderna, sostenible e integrada, donde todos los ciudadanos tengan acceso a servicios básicos de calidad.",
  "publicaciones": [
    "Construyendo el futuro: Propuestas para el desarrollo de la infraestructura en el Perú (2014)",
    "Manual de diseño de puentes (2005)"
  ],
  "reconocimientos": [
    "Premio a la mejor obra de ingeniería civil (2012)",
    "Reconocimiento por su aporte al desarrollo del distrito de Miraflores (2014)"
  ]
};

export const CandidatosCongreso = [
  {
    "id": "101",
    "nombre": "María Pérez Huamán",
    "edad": 45,
    "profesion": "Abogada",
    "educacion": "Universidad Nacional Mayor de San Marcos",
    "trayectoria": "Exregidora de Lima Metropolitana, con 15 años en defensa de derechos humanos y gestión municipal.",
    foto: require('@/assets/images/perfil.png'),
  },
  {
    "id": "102",
    "nombre": "Carlos Ramírez Quispe",
    "edad": 50,
    "profesion": "Economista",
    "educacion": "Pontificia Universidad Católica del Perú",
    "trayectoria": "Exdirector en el Ministerio de Economía, con más de 20 años como asesor financiero en el sector público y privado.",
    foto: require('@/assets/images/perfil.png'),
  },
  {
    "id": "103",
    "nombre": "Juan Carlos Gutiérrez",
    "edad": 58,
    "profesion": "Ingeniero Civil",
    "educacion": "Universidad Nacional de Ingeniería",
    "trayectoria": "Experto en gestión de proyectos de infraestructura, con más de 20 años de experiencia en el sector construcción.",
    foto: require('@/assets/images/perfil.png'),
  },
  {
    "id": "104",
    "nombre": "Ana María Flores",
    "edad": 42,
    "profesion": "Médica",
    "educacion": "Universidad Peruana Cayetano Heredia",
    "trayectoria": "Especialista en salud pública, con experiencia en gestión hospitalaria y programas de prevención de enfermedades.",
    foto: require('@/assets/images/perfil.png'),
  },
  {
    "id": "105",
    "nombre": "Luis Alberto Rodríguez",
    "edad": 55,
    "profesion": "Economista",
    "educacion": "Universidad del Pacífico",
    "trayectoria": "Consultor internacional en temas de desarrollo económico, con experiencia en organismos multilaterales.",
    foto: require('@/assets/images/perfil.png'),
  },
  {
    "id": "106",
    "nombre": "Sofia García Torres",
    "edad": 48,
    "profesion": "Abogada",
    "educacion": "Pontificia Universidad Católica del Perú",
    "trayectoria": "Especialista en derecho constitucional, con experiencia en el sector público y como asesora parlamentaria.",
    foto: require('@/assets/images/perfil.png'),
  },
  {
    "id": "107",
    "nombre": "Miguel Ángel Pérez",
    "edad": 60,
    "profesion": "Ingeniero Agrónomo",
    "educacion": "Universidad Nacional Agraria La Molina",
    "trayectoria": "Experto en desarrollo rural y gestión de recursos hídricos, con amplia experiencia en el sector agrícola.",
    foto: require('@/assets/images/perfil.png'),
  },
  {
    "id": "108",
    "nombre": "Laura Martínez",
    "edad": 39,
    "profesion": "Socióloga",
    "educacion": "Universidad Nacional Mayor de San Marcos",
    "trayectoria": "Investigadora social con enfoque en temas de género y desigualdad social.",
    foto: require('@/assets/images/perfil.png'),
  },
  {
    "id": "109",
    "nombre": "Pedro Castro",
    "edad": 51,
    "profesion": "Profesor",
    "educacion": "Pontificia Universidad Católica del Perú",
    "trayectoria": "Ex director de un colegio público, con amplia experiencia en pedagogía y gestión educativa.",
    foto: require('@/assets/images/perfil.png'),
  },
  {
    "id": "110",
    "nombre": "Elena Fernández",
    "edad": 46,
    "profesion": "Contadora",
    "educacion": "Universidad de Lima",
    "trayectoria": "Auditora financiera con experiencia en empresas privadas y en el sector público.",
    foto: require('@/assets/images/perfil.png'),
  }
];